-- Database creation.
CREATE DATABASE nyc_property;

-- Create a table to load raw csv files.
CREATE TABLE public.nyc_sales(
	"BOROUGH" TEXT,
	"NEIGHBORHOOD" TEXT,
	"BUILDING CLASS CATEGORY" TEXT,
	"TAX CLASS AT PRESENT" TEXT,
	"BLOCK" TEXT,
	"LOT" TEXT,
	"EASE-MENT" TEXT,
	"BUILDING CLASS AT PRESENT" TEXT,
	"ADDRESS" TEXT,
	"APARTMENT NUMBER" TEXT,
	"ZIP CODE" TEXT,
	"RESIDENTIAL UNITS" TEXT,
	"COMMERCIAL UNITS" TEXT,
	"TOTAL UNITS" TEXT,
	"LAND SQUARE FEET" TEXT,
	"GROSS SQUARE FEET" TEXT,
	"YEAR BUILT" TEXT,
	"TAX CLASS AT TIME OF SALE" TEXT,
	"BUILDING CLASS AT TIME OF SALE" TEXT,
	"SALE PRICE" TEXT,
	"SALE DATE" TEXT
);